[package]
name = "qr"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Minimal QR code generator for Zcash addresses"

[lib]
crate-type = ["lib"]

[dependencies]

[dev-dependencies]
